version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    ports:
      - "3306:3306"
    volumes:
      - banco_data:/var/lib/banco

volumes:
  banco_data: